import React from 'react';

const Bottom = () => {
    return (
        <div className='flex'  style={{width: 1800}}>
            <div>
                <div>
                    <div>
                        <ul className="w-40 bg-base-100">
                            <img src="https://i.ibb.co/3p524zX/Left.png" alt="sidebar" srcSet="" />
                        </ul>
                    </div>
                </div>
            </div>
            <div className='mt-10'>
                <div className="bg-[url('https://i.ibb.co/n6Gxyhh/Brush.png')] bg-no-repeat bg-center" >
                {/* <div style={{ backgroundImage: `url(https://i.ibb.co/n6Gxyhh/Brush.png)`, backgroundRepeat: 'no-repeat', marginLeft: 60 }}> */}
                <div className='text-blue-500 font-sans-serif font-bold text-5xl'>
                    <h1>Ash & Pikachu Arrive in</h1>
                    <h1>Pokémon Universe</h1>
                </div>
                </div>
                <div className='grid justify-center mx-auto grid-cols-2 gap-10 mt-10'>
                    <div className='text-start'>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, ab. Hic aut error nostrum consequuntur facilis praesentium, rem itaque. Cupiditate officia iure, qui magnam esse adipisci necessitatibus blanditiis tempora velit, beatae ea sequi illum aut quo maxime minima repellendus dolore nostrum excepturi provident. Beatae aliquam officia fugiat maxime quod quisquam delectus ad, adipisci, deleniti non sint quasi voluptatum quas explicabo aspernatur repellat atque, dicta quidem totam. Sequi molestiae, maiores voluptate officiis natus animi, dignissimos quisquam necessitatibus consectetur nemo accusantium asperiores, quasi autem iure hic. Ullam consequuntur placeat eligendi sequi. Quis dolores sapiente quod quisquam tenetur asperiores aut illo explicabo tempore?</p>
                        <p className='my-5'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi facilis vel doloremque quaerat delectus error tempore at, accusantium id nesciunt sunt eaque dolores iste blanditiis voluptatem odit qui? Molestias quo cum placeat officia repudiandae ex officiis, quibusdam, sed est beatae laudantium rerum cumque minus aut consectetur! Accusamus ab ad commodi impedit error corporis beatae reprehenderit eaque possimus, culpa odit. Cumque quisquam ratione beatae suscipit doloribus fugit aperiam aspernatur facere, soluta consequuntur quibusdam voluptate dolorum harum porro placeat. Obcaecati cum magni dolore vitae placeat, culpa suscipit sed quisquam at modi magnam libero alias est natus ex quam dolores odit dolor doloribus.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, harum error voluptates laboriosam corrupti sapiente fuga ea assumenda. Consectetur, repellendus aliquid? Ducimus esse nobis placeat veritatis, itaque mollitia sapiente animi impedit perspiciatis labore, tenetur beatae magnam nihil nostrum alias ipsum ipsa soluta aperiam suscipit? Beatae, aliquam ex? Rem, voluptas! Rem commodi voluptatibus magni animi, ex laboriosam ipsum illum voluptate. Fuga dolorem necessitatibus sunt labore maxime earum maiores nemo molestiae minus doloribus, vel expedita. Ducimus molestiae cumque tempore magni vitae modi esse porro eligendi iste blanditiis. Eaque ipsam at non quis sed vero accusantium explicabo maiores porro facilis, distinctio dicta aliquam!</p>
                        <p className='mt-5'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum consequatur delectus assumenda incidunt ad odio recusandae ullam. Veniam reprehenderit voluptatem ab fugiat, eligendi, perspiciatis, natus mollitia vero totam a harum maxime doloremque. Deserunt tenetur magni assumenda? Assumenda, cupiditate corporis illum incidunt, beatae sunt nostrum molestias consectetur magni nam ad dolorem animi deleniti sequi ea esse architecto sed vel ducimus aperiam, natus optio ipsum. Temporibus sint hic deleniti quae doloribus excepturi, dolore mollitia incidunt enim distinctio assumenda nostrum, totam amet magni modi voluptate quos minus? Excepturi at incidunt, dignissimos, ut maxime voluptate eaque velit error modi officia magnam corrupti cumque quibusdam vero sed. Odit non quae culpa natus qui nesciunt eaque porro similique sed magni quasi, amet, quis quas, fugiat labore fuga expedita minus nihil ea laudantium reiciendis unde vitae. Alias quo provident facilis dolorem quos dolor dicta hic consectetur sapiente quae totam impedit dolorum, sed, quibusdam illum. Impedit excepturi consectetur id magnam deleniti facilis, asperiores est laboriosam eaque earum. Voluptatum quis earum explicabo dolores tenetur. Fugit similique veniam consequuntur sunt exercitationem dignissimos, veritatis voluptatum, dolorem earum provident officiis blanditiis illo. Explicabo aspernatur, exercitationem quidem nemo, aut commodi placeat rerum perspiciatis quaerat odio, molestiae ipsam. Eius nihil laborum quam repellendus dignissimos dolorem corrupti aperiam recusandae maiores ex voluptatum totam ullam vero alias mollitia, amet quia nisi aliquam explicabo? Eius necessitatibus ipsum iste inventore itaque dolore accusamus. Quidem eos sint corporis praesentium neque commodi vitae rerum, doloribus dolorem pariatur dolore suscipit vel, nam ipsam modi qui facere expedita. Quis provident ipsum vel.</p>
                    </div>
                    <div className='text-start'>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, ab. Hic aut error nostrum consequuntur facilis praesentium, rem itaque. Cupiditate officia iure, qui magnam esse adipisci necessitatibus blanditiis tempora velit, beatae ea sequi illum aut quo maxime minima repellendus dolore nostrum excepturi provident. Beatae aliquam officia fugiat maxime quod quisquam delectus ad, adipisci, deleniti non sint quasi voluptatum quas explicabo aspernatur repellat atque, dicta quidem totam. Sequi molestiae, maiores voluptate officiis natus animi, dignissimos quisquam necessitatibus consectetur nemo accusantium asperiores, quasi autem iure hic. Ullam consequuntur placeat eligendi sequi. Quis dolores sapiente quod quisquam tenetur asperiores aut illo explicabo tempore?</p>
                        <p className='my-5'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi facilis vel doloremque quaerat delectus error tempore at, accusantium id nesciunt sunt eaque dolores iste blanditiis voluptatem odit qui? Molestias quo cum placeat officia repudiandae ex officiis, quibusdam, sed est beatae laudantium rerum cumque minus aut consectetur! Accusamus ab ad commodi impedit error corporis beatae reprehenderit eaque possimus, culpa odit. Cumque quisquam ratione beatae suscipit doloribus fugit aperiam aspernatur facere, soluta consequuntur quibusdam voluptate dolorum harum porro placeat. Obcaecati cum magni dolore vitae placeat, culpa suscipit sed quisquam at modi magnam libero alias est natus ex quam dolores odit dolor doloribus.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, harum error voluptates laboriosam corrupti sapiente fuga ea assumenda. Consectetur, repellendus aliquid? Ducimus esse nobis placeat veritatis, itaque mollitia sapiente animi impedit perspiciatis labore, tenetur beatae magnam nihil nostrum alias ipsum ipsa soluta aperiam suscipit? Beatae, aliquam ex? Rem, voluptas! Rem commodi voluptatibus magni animi, ex laboriosam ipsum illum voluptate. Fuga dolorem necessitatibus sunt labore maxime earum maiores nemo molestiae minus doloribus, vel expedita. Ducimus molestiae cumque tempore magni vitae modi esse porro eligendi iste blanditiis. Eaque ipsam at non quis sed vero accusantium explicabo maiores porro facilis, distinctio dicta aliquam!</p>
                        <p className='mt-5'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum consequatur delectus assumenda incidunt ad odio recusandae ullam. Veniam reprehenderit voluptatem ab fugiat, eligendi, perspiciatis, natus mollitia vero totam a harum maxime doloremque. Deserunt tenetur magni assumenda? Assumenda, cupiditate corporis illum incidunt, beatae sunt nostrum molestias consectetur magni nam ad dolorem animi deleniti sequi ea esse architecto sed vel ducimus aperiam, natus optio ipsum. Temporibus sint hic deleniti quae doloribus excepturi, dolore mollitia incidunt enim distinctio assumenda nostrum, totam amet magni modi voluptate quos minus? Excepturi at incidunt, dignissimos, ut maxime voluptate eaque velit error modi officia magnam corrupti cumque quibusdam vero sed. Odit non quae culpa natus qui nesciunt eaque porro similique sed magni quasi, amet, quis quas, fugiat labore fuga expedita minus nihil ea laudantium reiciendis unde vitae. Alias quo provident facilis dolorem quos dolor dicta hic consectetur sapiente quae totam impedit dolorum, sed, quibusdam illum. Impedit excepturi consectetur id magnam deleniti facilis, asperiores est laboriosam eaque earum. Voluptatum quis earum explicabo dolores tenetur. Fugit similique veniam consequuntur sunt exercitationem dignissimos, veritatis voluptatum, dolorem earum provident officiis blanditiis illo. Explicabo aspernatur, exercitationem quidem nemo, aut commodi placeat rerum perspiciatis quaerat odio, molestiae ipsam. Eius nihil laborum quam repellendus dignissimos dolorem corrupti aperiam recusandae maiores ex voluptatum totam ullam vero alias mollitia, amet quia nisi aliquam explicabo? Eius necessitatibus ipsum iste inventore itaque dolore accusamus. Quidem eos sint corporis praesentium neque commodi vitae rerum, doloribus dolorem pariatur dolore suscipit vel, nam ipsam modi qui facere expedita. Quis provident ipsum vel.</p>
                    </div>
                </div>
            </div>
            <div>
                <div>
                    <div>
                        <ul className="w-40 ml-10 bg-base-100">
                            <img src="https://i.ibb.co/3p524zX/Left.png" alt="sidebar" srcSet="" />
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Bottom;